# Generated by Django 4.2.4 on 2023-08-28 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('opening_hour', models.CharField(max_length=10)),
                ('closing_hours', models.CharField(max_length=10)),
                ('goggle_id', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
